roccor_file:
  2016preVFP: data/roch_corr/RoccoR2016aUL.txt
  2016postVFP: data/roch_corr/RoccoR2016bUL.txt
  '2017': data/roch_corr/RoccoR2017UL.txt
  '2018': data/roch_corr/RoccoR2018UL.txt # UL original
  # '2018': data/roch_corr/RoccoR2018.txt # rereco test
  2016_RERECO: data/roch_corr/RoccoR2016.txt
  '2017_RERECO': data/roch_corr/RoccoR2017.txt
  '2018_RERECO': data/roch_corr/RoccoR2018.txt
  2022preEE: data/roch_corr/RoccoR2018UL.txt
  2022postEE: data/roch_corr/RoccoR2018UL.txt
res_calib_path:
  2016preVFP:
    MC: data/res_calib/res_calib_MC_2016.root
    Data: data/res_calib/res_calib_Data_2016.root
  2016postVFP:
    MC: data/res_calib/res_calib_MC_2016.root
    Data: data/res_calib/res_calib_Data_2016.root
  '2017':
    MC: data/res_calib/res_calib_MC_2017.root
    Data: data/res_calib/res_calib_Data_2017.root
  '2018':
    MC: data/res_calib/res_calib_MC_2018.root
    Data: data/res_calib/res_calib_Data_2018.root
  2016_RERECO:
    MC: data/res_calib/res_calib_MC_2016.root
    Data: data/res_calib/res_calib_Data_2016.root
  '2017_RERECO':
    MC: data/res_calib/res_calib_MC_2017.root
    Data: data/res_calib/res_calib_Data_2017.root
  '2018_RERECO':
    MC: data/res_calib/res_calib_MC_2018.root
    Data: data/res_calib/res_calib_Data_2018.root
  2022preEE:
    MC: data/res_calib/res_calib_MC_2018.root
    Data: data/res_calib/res_calib_Data_2018.root
  2022postEE:
    MC: data/res_calib/res_calib_MC_2018.root
    Data: data/res_calib/res_calib_Data_2018.root
BS_res_calib_path:
  2016preVFP:
    MC: data/res_calib/res_calib_BS_correction_2016preVFP_nanoAODv12_MC.json
    Data: data/res_calib/res_calib_BS_correction_2016preVFP_nanoAODv12.json
  2016postVFP:
    MC: data/res_calib/res_calib_BS_correction_2016postVFP_nanoAODv12_MC.json
    Data: data/res_calib/res_calib_BS_correction_2016postVFP_nanoAODv12.json
  '2017':
    MC: data/res_calib/res_calib_BS_correction_2017_nanoAODv12_MC.json
    Data: data/res_calib/res_calib_BS_correction_2017_nanoAODv12.json
  '2018':
    MC: data/res_calib/res_calib_BS_correction_2018_nanoAODv12_MC.json
    Data: data/res_calib/res_calib_BS_correction_2018_nanoAODv12.json
  2016_RERECO: dummy
  '2017_RERECO': dummy
  '2018_RERECO': dummy
  2022preEE: dummy
  2022postEE: dummy
