jet_pt_cut:
  2016preVFP: 25.0
  2016postVFP: 25.0
  '2017': 25.0
  '2018': 25.0
  2016_RERECO: 25.0
  '2017_RERECO': 25.0
  '2018_RERECO': 25.0
  2022preEE: 25.0
  2022postEE: 25.0
jet_eta_cut:
  2016preVFP: 4.7
  2016postVFP: 4.7
  '2017': 4.7
  '2018': 4.7
  2016_RERECO: 4.7
  '2017_RERECO': 4.7
  '2018_RERECO': 4.7
  2022preEE: 4.7
  2022postEE: 4.7
jet_id:
  2016preVFP: tight # For 2016UL, we don't have loose ID, so make it just tight https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookNanoAOD#Jets
  2016postVFP: tight # For 2016UL, we don't have loose ID, so make it just tight https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookNanoAOD#Jets
  '2017': tight
  '2018': tight
  2016_RERECO: loose
  '2017_RERECO': tight
  '2018_RERECO': tight
  2022preEE: tight
  2022postEE: tight
jet_puid:
  2016preVFP: loose
  2016postVFP: loose
  '2017': loose
  '2018': loose
  2016_RERECO: loose
  '2017_RERECO': loose
  '2018_RERECO': loose
  2022preEE: loose
  2022postEE: loose
min_dr_mu_jet:
  2016preVFP: 0.4
  2016postVFP: 0.4
  '2017': 0.4
  '2018': 0.4
  2016_RERECO: 0.4
  '2017_RERECO': 0.4
  '2018_RERECO': 0.4
  2022preEE: 0.4
  2022postEE: 0.4
btag_loose_wp: # for DeepCSV, DeepJet is different
  2016preVFP: 0.2027
  2016postVFP: 0.1918
  '2017': 0.1355
  '2018': 0.1208 # central sources for UL https://btv-wiki.docs.cern.ch/ScaleFactors/UL2018/#ak4-b-tagging
  2016_RERECO: 0.2217  #central sources for RERECO https://twiki.cern.ch/twiki/bin/viewauth/CMS/BtagRecommendation102X
  '2017_RERECO': 0.1522
  '2018_RERECO': 0.1241
  2022preEE: 0.12
  2022postEE: 0.12
btag_medium_wp: # for DeepCSV, DeepJet is different
  2016preVFP: 0.6001
  2016postVFP: 0.5847
  '2017': 0.4506
  '2018': 0.4168
  2016_RERECO: 0.6321
  '2017_RERECO': 0.4941
  '2018_RERECO': 0.4184
  2022preEE: 0.4168
  2022postEE: 0.4168
softjet_dr2:
  2016preVFP: 0.16
  2016postVFP: 0.16
  '2017': 0.16
  '2018': 0.16
  2016_RERECO: 0.16
  '2017_RERECO': 0.16
  '2018_RERECO': 0.16
  2022preEE: 0.16
  2022postEE: 0.16
do_HemVeto:
  2016preVFP: false
  2016postVFP: false
  '2017': false
  '2018': true
  2016_RERECO: false
  '2017_RERECO': false
  '2018_RERECO': false
  2022preEE: false
  2022postEE: false
HemVeto_ratio: # ratio of HemVeto applicable run / total nevents for 2018UL
  2016preVFP: 0.0
  2016postVFP: 0.0
  '2017': 0.0
  '2018': 0.633396491
  2016_RERECO: 0.0
  '2017_RERECO': 0.0
  '2018_RERECO': 0.0
  2022preEE: 0.0
  2022postEE: 0.0
