nnlops_file:
  2016preVFP: data/NNLOPS_reweight.root
  2016postVFP: data/NNLOPS_reweight.root
  '2017': data/NNLOPS_reweight.root
  '2018': data/NNLOPS_reweight.root
  2016_RERECO: data/NNLOPS_reweight.root
  '2017_RERECO': data/NNLOPS_reweight.root
  '2018_RERECO': data/NNLOPS_reweight.root
  2022preEE: data/NNLOPS_reweight.root
  2022postEE: data/NNLOPS_reweight.root
btag_sf_json:
  2016preVFP: /cvmfs/cms.cern.ch/rsync/cms-nanoAOD/jsonpog-integration/POG/BTV/2016preVFP_UL/btagging.json.gz
  2016postVFP: /cvmfs/cms.cern.ch/rsync/cms-nanoAOD/jsonpog-integration/POG/BTV/2016postVFP_UL/btagging.json.gz
  '2017': /cvmfs/cms.cern.ch/rsync/cms-nanoAOD/jsonpog-integration/POG/BTV/2017_UL/btagging.json.gz
  '2018': /cvmfs/cms.cern.ch/rsync/cms-nanoAOD/jsonpog-integration/POG/BTV/2018_UL/btagging.json.gz
  2016_RERECO: /cvmfs/cms.cern.ch/rsync/cms-nanoAOD/jsonpog-integration/POG/BTV/2016preVFP_UL/btagging.json.gz
  '2017_RERECO': /cvmfs/cms.cern.ch/rsync/cms-nanoAOD/jsonpog-integration/POG/BTV/2017_UL/btagging.json.gz
  '2018_RERECO': /cvmfs/cms.cern.ch/rsync/cms-nanoAOD/jsonpog-integration/POG/BTV/2018_UL/btagging.json.gz
  2022preEE: /cvmfs/cms.cern.ch/rsync/cms-nanoAOD/jsonpog-integration/POG/BTV/2022_Summer22EE/btagging.json.gz
  2022postEE: /cvmfs/cms.cern.ch/rsync/cms-nanoAOD/jsonpog-integration/POG/BTV/2022_Summer22EE/btagging.json.gz
btag_sf_csv:
  2016preVFP: data/btag/DeepCSV_2016LegacySF_V1.csv
  2016postVFP: data/btag/DeepCSV_2016LegacySF_V1.csv
  '2017': data/btag/DeepCSV_106XUL17SF.csv
  '2018': data/btag/DeepCSV_106XUL18SF.csv
  2016_RERECO: data/btag/DeepCSV_2016LegacySF_V1.csv
  '2017_RERECO': data/btag/DeepCSV_94XSF_V5_B_F.csv
  '2018_RERECO': data/btag/DeepCSV_102XSF_V1.csv
  2022preEE: data/btag/DeepCSV_106XUL18SF.csv
  2022postEE: data/btag/DeepCSV_106XUL18SF.csv
pu_file_data:
  2016preVFP: data/pileup/puData2016_UL_withVar.root
  2016postVFP: data/pileup/puData2016_UL_withVar.root
  '2017': data/pileup/puData2017_UL_withVar.root
  '2018': data/pileup/puData2018_UL_withVar.root
  2016_RERECO: data/pileup/PileupData_GoldenJSON_Full2016.root
  '2017_RERECO': data/pileup/puData2017_withVar.root
  '2018_RERECO': data/pileup/puData2018_withVar.root
  2022preEE: dummy_only_pu_file_mc_is_needed
  2022postEE: dummy_only_pu_file_mc_is_needed
pu_file_mc: # source https://github.com/cms-sw/cmssw/blob/CMSSW_10_6_X/SimGeneral/MixingModule/python/mix_2018_25ns_UltraLegacy_PoissonOOTPU_cfi.py
  2016preVFP: data/pileup/mix_2016_25ns_UltraLegacy_PoissonOOTPU_cfi.yaml
  2016postVFP: data/pileup/mix_2016_25ns_UltraLegacy_PoissonOOTPU_cfi.yaml
  '2017': data/pileup/mix_2017_25ns_UltraLegacy_PoissonOOTPU_cfi.yaml
  '2018': data/pileup/mix_2018_25ns_UltraLegacy_PoissonOOTPU_cfi.yaml
  2016_RERECO: data/pileup/pileup_profile_Summer16.root
  '2017_RERECO': data/pileup/mcPileup2017.root
  '2018_RERECO': data/pileup/mcPileup2018.root
  2022preEE: data/pileup/2022_Summer22/puWeights.json.gz
  2022postEE: data/pileup/2022_Summer22EE/puWeights.json.gz
muSFFileList:
  2016preVFP:
  - id:
    - data/muon_sf/year2016/MuonSF_Run2016_UL_HIPM_ID.root
    - NUM_MediumID_DEN_TrackerMuons_abseta_pt
    iso:
    - data/muon_sf/year2016/MuonSF_Run2016_UL_HIPM_ISO.root
    - NUM_TightRelIso_DEN_MediumID_abseta_pt
    trig:
    - data/muon_sf/mu2016/EfficienciesStudies_2016_trigger_EfficienciesAndSF_RunBtoF.root
    - IsoMu24_OR_IsoTkMu24_PtEtaBins/efficienciesDATA/abseta_pt_DATA
    - IsoMu24_OR_IsoTkMu24_PtEtaBins/efficienciesMC/abseta_pt_MC
    scale: 1.0
  2016postVFP:
  - id:
    - data/muon_sf/year2016/MuonSF_Run2016_UL_ID.root
    - NUM_MediumID_DEN_TrackerMuons_abseta_pt
    iso:
    - data/muon_sf/year2016/MuonSF_Run2016_UL_ISO.root
    - NUM_TightRelIso_DEN_MediumID_abseta_pt
    trig:
    - data/muon_sf/mu2016/EfficienciesStudies_2016_trigger_EfficienciesAndSF_RunGtoH.root
    - IsoMu24_OR_IsoTkMu24_PtEtaBins/efficienciesDATA/abseta_pt_DATA
    - IsoMu24_OR_IsoTkMu24_PtEtaBins/efficienciesMC/abseta_pt_MC
    scale: 1.0
  '2017':
  - id:
    - data/muon_sf/year2017/MuonSF_Run2017_UL_ID.root
    - NUM_MediumID_DEN_TrackerMuons_abseta_pt
    iso:
    - data/muon_sf/year2017/MuonSF_Run2017_UL_ISO.root
    - NUM_TightRelIso_DEN_MediumID_abseta_pt
    trig:
    - data/muon_sf/mu2017/EfficienciesAndSF_RunBtoF_Nov17Nov2017.root
    - IsoMu27_PtEtaBins/efficienciesDATA/abseta_pt_DATA
    - IsoMu27_PtEtaBins/efficienciesMC/abseta_pt_MC
    scale: 1.0
  '2018':
  - id:
    - data/muon_sf/year2018/MuonSF_Run2018_UL_ID.root # UL
    - NUM_MediumID_DEN_TrackerMuons_abseta_pt # UL
    # - data/muon_sf/year2018/RunABCD_SF_ID.root # rereco
    # - NUM_MediumID_DEN_genTracks_pt_abseta # rereco
    iso:
    - data/muon_sf/year2018/MuonSF_Run2018_UL_ISO.root # UL
    - NUM_TightRelIso_DEN_MediumID_abseta_pt # UL
    # - data/muon_sf/year2018/RunABCD_SF_ISO.root # rereco
    # - NUM_TightRelIso_DEN_MediumID_pt_abseta # rereco
    trig:
    - data/muon_sf/mu2018/EfficienciesStudies_2018_trigger_EfficienciesAndSF_2018Data_BeforeMuonHLTUpdate.root
    - IsoMu24_PtEtaBins/efficienciesDATA/abseta_pt_DATA
    - IsoMu24_PtEtaBins/efficienciesMC/abseta_pt_MC
    scale: 0.14981586876464678 # 8.95 / 59.74
  - id:
    - data/muon_sf/year2018/MuonSF_Run2018_UL_ID.root # UL
    - NUM_MediumID_DEN_TrackerMuons_abseta_pt # UL
    # - data/muon_sf/year2018/RunABCD_SF_ID.root # rereco
    # - NUM_MediumID_DEN_genTracks_pt_abseta # rereco
    iso:
    - data/muon_sf/year2018/MuonSF_Run2018_UL_ISO.root # UL
    - NUM_TightRelIso_DEN_MediumID_abseta_pt # UL
    # - data/muon_sf/year2018/RunABCD_SF_ISO.root # rereco
    # - NUM_TightRelIso_DEN_MediumID_pt_abseta # rereco
    trig:
    - data/muon_sf/mu2018/EfficienciesStudies_2018_trigger_EfficienciesAndSF_2018Data_AfterMuonHLTUpdate.root
    - IsoMu24_PtEtaBins/efficienciesDATA/abseta_pt_DATA
    - IsoMu24_PtEtaBins/efficienciesMC/abseta_pt_MC
    scale: 0.8501841312353532 # 50.79 / 59.74
  2016_RERECO:
  - id:
    - data/muon_sf/year2016/RunBCDEF_SF_ID.root
    - NUM_MediumID_DEN_genTracks_eta_pt
    iso:
    - data/muon_sf/year2016/RunBCDEF_SF_ISO.root
    - NUM_TightRelIso_DEN_MediumID_eta_pt
    trig:
    - data/muon_sf/mu2016/EfficienciesStudies_2016_trigger_EfficienciesAndSF_RunBtoF.root
    - IsoMu24_OR_IsoTkMu24_PtEtaBins/efficienciesDATA/abseta_pt_DATA
    - IsoMu24_OR_IsoTkMu24_PtEtaBins/efficienciesMC/abseta_pt_MC
    scale: 0.552197802
  - id:
    - data/muon_sf/year2016/RunGH_SF_ID.root
    - NUM_MediumID_DEN_genTracks_eta_pt
    iso:
    - data/muon_sf/year2016/RunGH_SF_ISO.root
    - NUM_TightRelIso_DEN_MediumID_eta_pt
    trig:
    - data/muon_sf/mu2016/EfficienciesStudies_2016_trigger_EfficienciesAndSF_RunGtoH.root
    - IsoMu24_OR_IsoTkMu24_PtEtaBins/efficienciesDATA/abseta_pt_DATA
    - IsoMu24_OR_IsoTkMu24_PtEtaBins/efficienciesMC/abseta_pt_MC
    scale: 0.447802198
  '2017_RERECO':
  - id:
    - data/muon_sf/year2017/RunBCDEF_SF_ID.root
    - NUM_MediumID_DEN_genTracks_pt_abseta
    iso:
    - data/muon_sf/year2017/RunBCDEF_SF_ISO.root
    - NUM_TightRelIso_DEN_MediumID_pt_abseta
    trig:
    - data/muon_sf/mu2017/EfficienciesAndSF_RunBtoF_Nov17Nov2017.root
    - IsoMu27_PtEtaBins/efficienciesDATA/abseta_pt_DATA
    - IsoMu27_PtEtaBins/efficienciesMC/abseta_pt_MC
    scale: 1.0
  '2018_RERECO':
  - id:
    - data/muon_sf/year2018/RunABCD_SF_ID.root
    - NUM_MediumID_DEN_genTracks_pt_abseta
    iso:
    - data/muon_sf/year2018/RunABCD_SF_ISO.root
    - NUM_TightRelIso_DEN_MediumID_pt_abseta
    trig:
    - data/muon_sf/mu2018/EfficienciesStudies_2018_trigger_EfficienciesAndSF_2018Data_BeforeMuonHLTUpdate.root
    - IsoMu24_PtEtaBins/efficienciesDATA/abseta_pt_DATA
    - IsoMu24_PtEtaBins/efficienciesMC/abseta_pt_MC
    scale: 0.149815869
  - id:
    - data/muon_sf/year2018/RunABCD_SF_ID.root
    - NUM_MediumID_DEN_genTracks_pt_abseta
    iso:
    - data/muon_sf/year2018/RunABCD_SF_ISO.root
    - NUM_TightRelIso_DEN_MediumID_pt_abseta
    trig:
    - data/muon_sf/mu2018/EfficienciesStudies_2018_trigger_EfficienciesAndSF_2018Data_AfterMuonHLTUpdate.root
    - IsoMu24_PtEtaBins/efficienciesDATA/abseta_pt_DATA
    - IsoMu24_PtEtaBins/efficienciesMC/abseta_pt_MC
    scale: 0.850184131
  2022preEE:
  - id:
    - data/muon_sf/year2017/MuonSF_Run2017_UL_ID.root
    - NUM_MediumID_DEN_TrackerMuons_abseta_pt
    iso:
    - data/muon_sf/year2017/MuonSF_Run2017_UL_ISO.root
    - NUM_TightRelIso_DEN_MediumID_abseta_pt
    trig:
    - data/muon_sf/mu2017/EfficienciesAndSF_RunBtoF_Nov17Nov2017.root
    - IsoMu27_PtEtaBins/efficienciesDATA/abseta_pt_DATA
    - IsoMu27_PtEtaBins/efficienciesMC/abseta_pt_MC
    scale: 1.0
  2022postEE:
  - id:
    - data/muon_sf/year2017/MuonSF_Run2017_UL_ID.root
    - NUM_MediumID_DEN_TrackerMuons_abseta_pt
    iso:
    - data/muon_sf/year2017/MuonSF_Run2017_UL_ISO.root
    - NUM_TightRelIso_DEN_MediumID_abseta_pt
    trig:
    - data/muon_sf/mu2017/EfficienciesAndSF_RunBtoF_Nov17Nov2017.root
    - IsoMu27_PtEtaBins/efficienciesDATA/abseta_pt_DATA
    - IsoMu27_PtEtaBins/efficienciesMC/abseta_pt_MC
    scale: 1.0
zpt_weights_file:
  # 2016preVFP: data/reweight_zpt_2018_nJetBinned_new.histo.root # Valerie's zpt
  # 2016postVFP: data/reweight_zpt_2018_nJetBinned_new.histo.root # Valerie's zpt
  2016preVFP: data/zpt_weights.histo.json # Dmitry's zpt
  2016postVFP: data/zpt_weights.histo.json # Dmitry's zpt
  # '2017': data/reweight_zpt_2018_nJetBinned_new.histo.root
  '2017': data/zpt_weights.histo.json # Dmitry's zpt
  # '2018': data/reweight_zpt_2018_nJetBinned_new.histo.root # Valerie's zpt
  '2018': data/zpt_weights.histo.json # Dmitry's zpt
  2016_RERECO: data/zpt_weights.histo.json # FIXME
  '2017_RERECO': data/zpt_weights.histo.json # FIXME
  '2018_RERECO': data/zpt_weights.histo.json # FIXME
zpt_weights_file_valerie:
  2016preVFP: data/reweight_zpt_2018_nJetBinned_new.histo.root # Valerie's zpt
  2016postVFP: data/reweight_zpt_2018_nJetBinned_new.histo.root # Valerie's zpt
  '2017': data/reweight_zpt_2018_nJetBinned_new.histo.root
  '2018': data/reweight_zpt_2018_nJetBinned_new.histo.root # Valerie's zpt
  2016_RERECO: data/zpt_weights.histo.json # FIXME
  '2017_RERECO': data/zpt_weights.histo.json # FIXME
  '2018_RERECO': data/zpt_weights.histo.json # FIXME
new_zpt_weights_file:
  2016preVFP: data/zpt_rewgt/fitting/zpt_rewgt_params_minnlo.yaml # New zpt rewgt March 30 2025
  2016postVFP: data/zpt_rewgt/fitting/zpt_rewgt_params_minnlo.yaml # New zpt rewgt March 30 2025
  '2017': data/zpt_rewgt/fitting/zpt_rewgt_params_minnlo.yaml # New zpt rewgt March 30 2025
  '2018': data/zpt_rewgt/fitting/zpt_rewgt_params_minnlo.yaml # New zpt rewgt March 30 2025
  # 2016preVFP: data/zpt_rewgt/fitting/zpt_rewgt_params_amcnlo.yaml # New zpt rewgt March 30 2025
  # 2016postVFP: data/zpt_rewgt/fitting/zpt_rewgt_params_amcnlo.yaml # New zpt rewgt March 30 2025
  # '2017': data/zpt_rewgt/fitting/zpt_rewgt_params_amcnlo.yaml # New zpt rewgt March 30 2025
  # '2018': data/zpt_rewgt/fitting/zpt_rewgt_params_amcnlo.yaml # New zpt rewgt March 30 2025
  2016_RERECO: data/zpt_rewgt/fitting/zpt_rewgt_params.yaml
  '2017_RERECO': data/zpt_rewgt/fitting/zpt_rewgt_params.yaml
  '2018_RERECO': data/zpt_rewgt/fitting/zpt_rewgt_params.yaml
  2022preEE: data/reweight_zpt_2018_nJetBinned_new.histo.root
  2022postEE: data/reweight_zpt_2018_nJetBinned_new.histo.root
jetpuid_sf_file: # old method as of Dec 16 2024,
  2016preVFP: data/PUID_106XTraining_ULRun2_EffSFandUncties_v1.root
  2016postVFP: data/PUID_106XTraining_ULRun2_EffSFandUncties_v1.root
  '2017': data/PUID_106XTraining_ULRun2_EffSFandUncties_v1.root
  '2018': data/PUID_106XTraining_ULRun2_EffSFandUncties_v1.root
  2016_RERECO: data/PUIDMaps.root
  '2017_RERECO': data/PUIDMaps.root
  '2018_RERECO': data/PUIDMaps.root
  2022preEE: data/PUID_106XTraining_ULRun2_EffSFandUncties_v1.root
  2022postEE: data/PUID_106XTraining_ULRun2_EffSFandUncties_v1.root
jmar_sf_file:
  2016preVFP: /cvmfs/cms.cern.ch/rsync/cms-nanoAOD/jsonpog-integration/POG/JME/2016preVFP_UL/jmar.json.gz
  2016postVFP: /cvmfs/cms.cern.ch/rsync/cms-nanoAOD/jsonpog-integration/POG/JME/2016postVFP_UL/jmar.json.gz
  '2017': /cvmfs/cms.cern.ch/rsync/cms-nanoAOD/jsonpog-integration/POG/JME/2017_UL/jmar.json.gz # while this is listed, we use jetpuid_sf_file for 2017 (old method)
  '2018': /cvmfs/cms.cern.ch/rsync/cms-nanoAOD/jsonpog-integration/POG/JME/2018_UL/jmar.json.gz
  # 2016preVFP: data/POG/JME/2016preVFP_UL/jmar.json.gz
  # 2016postVFP: data/POG/JME/2016postVFP_UL/jmar.json.gz
  # '2017': data/POG/JME/2017_UL/jmar.json.gz # while this is listed, we use jetpuid_sf_file for 2017 (old method)
  # '2018': data/POG/JME/2018_UL/jmar.json.gz
  2016_RERECO: dummy
  '2017_RERECO': dummy
  '2018_RERECO': dummy
  2022preEE: dummy
  2022postEE: dummy
